{% set name = "ydata-profiling" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ydata-profiling-{{ version }}.tar.gz
  sha256: 739c899ce689edaa08042a1fba98b591f4bbf7ecf0b66a4d6012d01de4cab091

build:
  entry_points:
    - ydata_profiling = ydata_profiling.controller.console:main
    - pandas_profiling = ydata_profiling.controller.console:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - scipy >=1.4.1,<1.11
    - pandas >1.1,<2.1,!=1.4.0
    - matplotlib-base >=3.2,<4
    - pydantic >=1.8.1,<2
    - pyyaml >=5.0.0,<6.1
    - jinja2 >=2.11.1,<3.2
    - visions ==0.7.5
    - numpy >=1.16.0,<1.24
    - htmlmin ==0.1.12
    - phik >=0.11.1,<0.13
    - requests >=2.24.0,<3
    - tqdm >=4.48.2,<5
    - seaborn >=0.10.1,<0.13
    - multimethod >=1.4,<2
    - statsmodels >=0.13.2,<1
    - typeguard >=2.13.2,<3
    - imagehash ==4.3.1
    - wordcloud >=1.8.2.2
    - dacite >=1.6

  run_constrained:
    - jupyter-client >=5.3.4
    - jupyter-core >=4.6.3
    - tangled-up-in-unicode 0.2.0

test:
  imports:
    - pandas_profiling
    - ydata_profiling
  commands:
 #   - pip check
    - ydata_profiling --help
    - pandas_profiling --help
  requires:
    - pip

about:
  home: https://github.com/ydataai/ydata-profiling
  summary: Generate profile report for pandas DataFrame
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://ydata-profiling.ydata.ai

extra:
  recipe-maintainers:
    - rxm7706
